// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAtPISpdO64BtI1CWq8fh9hGx2cTbQ3qE',
    appId: '1:992286831331:web:29e32cbfbde76de3128bd6',
    messagingSenderId: '992286831331',
    projectId: 'glucotrack-872bb',
    authDomain: 'glucotrack-872bb.firebaseapp.com',
    storageBucket: 'glucotrack-872bb.firebasestorage.app',
    measurementId: 'G-64VK8E3FN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCewCvRZG_cZfoINNyv3ebBP-KsmbwZPbI',
    appId: '1:992286831331:android:1aaeb220848309b6128bd6',
    messagingSenderId: '992286831331',
    projectId: 'glucotrack-872bb',
    storageBucket: 'glucotrack-872bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB6f7qi72soe4Ed0tgmblOEEnl0BR_wzE',
    appId: '1:992286831331:ios:c20c6c0d0bef9034128bd6',
    messagingSenderId: '992286831331',
    projectId: 'glucotrack-872bb',
    storageBucket: 'glucotrack-872bb.firebasestorage.app',
    iosBundleId: 'com.example.untitled10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB6f7qi72soe4Ed0tgmblOEEnl0BR_wzE',
    appId: '1:992286831331:ios:c20c6c0d0bef9034128bd6',
    messagingSenderId: '992286831331',
    projectId: 'glucotrack-872bb',
    storageBucket: 'glucotrack-872bb.firebasestorage.app',
    iosBundleId: 'com.example.untitled10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAtPISpdO64BtI1CWq8fh9hGx2cTbQ3qE',
    appId: '1:992286831331:web:0dd99f6a7ca692fa128bd6',
    messagingSenderId: '992286831331',
    projectId: 'glucotrack-872bb',
    authDomain: 'glucotrack-872bb.firebaseapp.com',
    storageBucket: 'glucotrack-872bb.firebasestorage.app',
    measurementId: 'G-VF7K9BZYQJ',
  );
}
